### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by tna76874** [jneem/scribl#6]
Hi,
thank you for your project!

The mp4-export with the flathub-flatpak install does not work. Is there a way to get this working?

Regards

edit: actually it does also not work with the compiled version
`error Failed to create element from factory name`

**Comment by jneem** [comment]
Thanks for the feedback. I'm guessing that this is caused by some missing gstreamer plugins (which is puzzling for the flatpak one, because I thought I packaged the plugins). Could you try installing the "ugly" gstreamer plugins? If you're on ubuntu or debian, that's a package called `gstreamer1.0-plugins-ugly`.

**Comment by tna76874** [comment]
Thank you for your answer - I installed now version `1.14.5-0ubuntu1~18.04.1`. With the compiled version I can export now videos - with the flatpak version it is not working. Do you think it is possible to get the flatpak version running? I do like this nice piece of software!

**Comment by jneem** [comment]
Great, thanks for checking! I will improve those error messages. I'll also try to get the flatpak working -- it's quite old by now, and it definitely needs an update, but I haven't had time for it...

**Comment by jneem** [comment]
I've updated the flatpak package, and I think this is fixed now. Please re-open if it isn't.

**Comment by tna76874** [comment]
Thank you - works like a charm now :)
